language: minimal
branches:
  only:
    - master
env:
  PROJECT: httpd-asm
before_install:
  - pushd $PROJECT
  - ./bin/ci/before-install
  - popd
script:
  - pushd $PROJECT
  - ./bin/ci/script
  - popd
